### ISSUE TITLE
Burp freezes after clicking on Reset

### ISSUE THREAD

**Issue by Hipapheralkus** [augustd/burp-suite-error-message-checks#30]
Hi,
I have following Load rules from URL which has been there since 1.x version:
`file:///C:\Burp\burp-suite-error-message-checks.tab`
When I open Burp, update extension, in the Output I can see is loaded properly from the file. There is nothing in the Errors console. So far so good, but when I press Reset (to load the default URL), the entire Burp instance freezes and I need to force-kill it. This is only happening since the newest update.

**Comment by augustd** [comment]
This is probably due to a bad network connection. When you click reset the extension tries to load the match rules from the remote location. If you don't have a network path to that location the app will freeze waiting for the response to timeout.

I'll see what I can do about loading the rules in a separate thread so at least the rest of the UI will function while waiting for a response.
